spring.application.name=bookstore-management-system
server.port=8080
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
server.error.whitelabel.enabled=false

bookstore.storage.root=storage
bookstore.storage.customers-file=customers.txt
bookstore.storage.admins-file=admins.txt
bookstore.storage.books-file=books.txt
bookstore.storage.carts-file=carts.txt
bookstore.storage.orders-file=orders.txt
bookstore.storage.audit-file=audit-log.txt
